[env]
TERM = "xterm-256color"

[window]
padding.x = 12
padding.y = 12

decorations = "Buttonless"

opacity = 0.9
blur = true

option_as_alt = "Both"

[font]
offset.x = 1
offset.y = 0

normal.family = "MesloLGSDZ Nerd Font"
normal.style = "Bold"

size = 15

[general]
import = [
    "~/.config/alacritty/themes/catppuccin_frappe.toml",
]
